---
title: "SpatialAnalytics_YieldGaps"
format: html
fig-dpi: 300
fig-width: 8.88
fig-align: center
fig-height: 5

self-contained: true
author: Maxwell Mkondiwa
editor: visual
toc: true
toc-location: left
number-sections: true
execute: 
  message: false
  warning: false
  echo: true
---

# Geoadditive stochastic frontier analysis

## Estimation

```{r}

# Geadditive R package

library(rio)
LDS_wheat_public_cleaned=import("LDS_wheat_public_cleaned.csv")
library(tidyr)
#LDSestim_gam=LDSestim %>% drop_na()
library(dsfa)
library(mgcv)

#Write formulae for parameters
mu_formula<-L.tonPerHectare~Nperha+wc2.1_30s_elev+s(O.largestPlotGPS.Longitude, 
    O.largestPlotGPS.Latitude, by = Weedmanaged) 

sigma_v_formula<-~1+temp+precip

#+s(G.q5305_irrigTimes, bs="ps")+
sigma_u_formula<-~-1+
s(O.largestPlotGPS.Longitude, 
    O.largestPlotGPS.Latitude, by = Sowing_Date_Early) 


  
#s(O.largestPlotGPS.Longitude,O.largestPlotGPS.Latitude, bs = 'gp', k = 100, m = 2)
s=-1
#"O.largestPlotGPS.Latitude"                   "O.largestPlotGPS.Longitude"
#Fit model
model<-mgcv::gam(formula=list(mu_formula, sigma_v_formula, sigma_u_formula),
                 data=LDS_wheat_public_cleaned, family=normhnorm(s=s), optimizer = c("efs"))

#Model summary
summary(model)



#LDS_wheat_public_cleaned$eff=efficiency(model, type="battese")

#Get elasticities
#els=elasticity(model)

plot(model, select=1) #Estimated function
plot(model, select=2)
```

## Geoadditive kriging
```{r}

 pred <- expand.grid(O.largestPlotGPS.Longitude = seq(82, 89, length = 100),O.largestPlotGPS.Latitude = seq(24,28, length = 100))

pred$Sowing_Date_Early=1
pred$Nperha=mean(model$model$Nperha)
pred$wc2.1_30s_elev=mean(model$model$wc2.1_30s_elev)
pred$Weedmanaged=1
pred$temp=mean(model$model$temp)
pred$precip=mean(model$model$precip)
#pred$PumpEnergySource=Diesel
#pred$G.q5305_irrigTimes=mean(model$model$G.q5305_irrigTimes)

pred2 <- expand.grid(O.largestPlotGPS.Longitude = seq(82, 89, length = 100),O.largestPlotGPS.Latitude = seq(24,28, length = 100))

pred2$Sowing_Date_Early=0

pred2$Nperha=mean(model$model$Nperha)
pred2$wc2.1_30s_elev=mean(model$model$wc2.1_30s_elev)
pred2$Weedmanaged=1
pred2$temp=mean(model$model$temp)
pred2$precip=mean(model$model$precip)
#pred2$PumpEnergySource=Diesel
#pred2$G.q5305_irrigTimes=mean(model$model$G.q5305_irrigTimes)

yield_fit=model$fitted.values

tau_hat <- predict(model,newdata=pred)
tau_hat2 <- predict(model,newdata=pred2)

fit = predict(model,type="terms")

tau_hat=as.data.frame(tau_hat)
tau_hat2=as.data.frame(tau_hat2)

names(tau_hat)[1:3]=c("mu_1","sigma_v_1","sigma_u_1")
names(tau_hat2)[1:3]=c("mu_2","sigma_v_2","sigma_u_2")

#pred_tau_hat=cbind(pred,tau_hat,tau_hat2)

pred_tau_hat=cbind(pred,tau_hat)
pred_tau_hat=as.data.frame(pred_tau_hat)

pred_tau_hat$sowing_yield_gain=pred_tau_hat$mu_1-tau_hat2$mu_2

pred_tau_hat=subset(pred_tau_hat,select=c("O.largestPlotGPS.Longitude","O.largestPlotGPS.Latitude","sigma_u_1"))

library(terra)
myras <- rast(pred_tau_hat, type="xyz")
plot(myras)


# Masking
library(raster)
 myras2=raster(myras)
 
 
 
library(geodata)

India=gadm(country="IND", level=2, path="shp")
plot(India)
India_aoi=subset(India,India$NAME_1=="Bihar"|India$NAME_2%in%c("Ballia","Chandauli","Deoria","Ghazipur","Kushinagar","Maharajganj","Mau","Siddharth Nagar","Gorakhpur"))

plot(India_aoi)

plot(India_aoi, add=TRUE)

library(sf)
India_aoi_sf=st_as_sf(India_aoi)
library(mapview)

mapview(India_aoi_sf)

library(sf)
India_aoi_sf_dis=st_union(India_aoi_sf)


library(sf)
India_aoi_sf_dis_sp=as_Spatial(India_aoi_sf_dis)
myras2=mask(myras2,India_aoi_sf_dis_sp)
plot(myras2)
```

